### ISSUE TITLE
Link is expired

### ISSUE THREAD

**Issue by Shiva108** [improsec/ImprosecPasswordAuditor#1]
https://improsec-my.sharepoint.com/:u:/p/vca/EfkYRlAhwlNKuoKOKA6ZG2sByZKnVXfz9bk1vpAFlILxow
![image](https://user-images.githubusercontent.com/13223532/149910650-480d7e99-fdbf-425c-a9ad-3a9f60fdcead.png)

**Comment by ghost** [comment]
Hello Shiva,

Sorry for the delay - link has been updated :)
