### ISSUE TITLE
Link has expired

### ISSUE THREAD

**Issue by martclau** [improsec/ImprosecPasswordAuditor#3]
This link does not work.

Go to [Improsec Leaked Password List](https://improsec-my.sharepoint.com/:u:/p/vca/EfkYRlAhwlNKuoKOKA6ZG2sByZKnVXfz9bk1vpAFlILxow).

**Comment by ghost** [comment]
Hello martclau,

I've updated the link to the newest version of the leaked password list from Troy Hunt :)
